### ISSUE TITLE
An animal toString sometimes appear when doing nothing for the current turn

### ISSUE THREAD

**Issue by byoan** [byoan/Zoo#56]
Not doing anything this turn ...

Turn n°3 ended.

   Animal {
       Specie: Fish  |  Is in an enclosure : Yes
       Hunger: 100%  |  Currently sleeping: No  |  Health: 100%
       Sex: Male  |  Weight: 2369.0g  |  Size: 15.0cm  |  Age: Young
       Started pregnancy at turn: -  |  Pregnancy duration: 5 turns
       Already hatched: Yes
    }
Turn n°4 started.

**Comment by Kur0n33k0** [comment]
Fixed in #60
